<?php

/**
 * @file
 * zonedate Module.
 */

 /**
 * Implements hook_preprocess_page().
 */
function zonedate_preprocess(&$variables) {
    $config = \Drupal::config('zonedate.settings');
    $city = $config->get("city");
    $country = $config->get("country");
    /* @var \Drupal\zonedate\ZoneDateService $zoneDateService */
    $zoneDateService = \Drupal::service('zonedate_service.datetime');
    $dateAndTime = $zoneDateService->getTime();
    //setting variables to be used in template
    $variables['zonedate_city'] = $city ;
    $variables['zonedate_country'] = $country ;
    $variables['zonedate_dateAndTime'] = $dateAndTime ;
}